title    verbose boot (debug serial)
sort-key 04
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisolabel=BNASEC300 cow_label=persistence console=tty0 console=ttyS0,115200n8 ignore_loglevel
